In [ ]:
#Without dataset
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
dataset=load_iris()

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(dataset["data"],dataset["target"],random_state=0)

In [ ]:
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train,y_train)
for i in range(len(X_test)):
  x=X_test[i]
  x_new=np.array([x])
  prediction=kn.predict(x_new)
  print("TARGET=",y_test[i],dataset["target_names"],[y_test[i]],"PREDICTED=",prediction,dataset["target_names"][prediction])
  print(kn.score(X_test,y_test))

TARGET= 2 ['setosa' 'versicolor' 'virginica'] [2] PREDICTED= [2] ['virginica']
0.9736842105263158
TARGET= 1 ['setosa' 'versicolor' 'virginica'] [1] PREDICTED= [1] ['versicolor']
0.9736842105263158
TARGET= 0 ['setosa' 'versicolor' 'virginica'] [0] PREDICTED= [0] ['setosa']
0.9736842105263158
TARGET= 2 ['setosa' 'versicolor' 'virginica'] [2] PREDICTED= [2] ['virginica']
0.9736842105263158
TARGET= 0 ['setosa' 'versicolor' 'virginica'] [0] PREDICTED= [0] ['setosa']
0.9736842105263158
TARGET= 2 ['setosa' 'versicolor' 'virginica'] [2] PREDICTED= [2] ['virginica']
0.9736842105263158
TARGET= 0 ['setosa' 'versicolor' 'virginica'] [0] PREDICTED= [0] ['setosa']
0.9736842105263158
TARGET= 1 ['setosa' 'versicolor' 'virginica'] [1] PREDICTED= [1] ['versicolor']
0.9736842105263158
TARGET= 1 ['setosa' 'versicolor' 'virginica'] [1] PREDICTED= [1] ['versicolor']
0.9736842105263158
TARGET= 1 ['setosa' 'versicolor' 'virginica'] [1] PREDICTED= [1] ['versicolor']
0.9736842105263158
TARGET= 2 ['setosa' 'vers

In [ ]:
#With Dataset
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from sklearn import datasets

In [ ]:
iris=datasets.load_iris()
iris_data=iris.data
iris_labels=iris.target
print(iris_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
x_train, x_test, y_train, y_test=(train_test_split(iris_data, iris_labels, test_size=0.20))

In [ ]:
classifier=KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)
print("accuracy is")
print(classification_report(y_test, y_pred))

accuracy is
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.89      0.89      0.89         9
           2       0.92      0.92      0.92        12

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30

